name: Build Test and Artifact

on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
    inputs:
      perform_action:
        required: true
        type: choice
        options:
        - build
        - release
        default: build

jobs:
  build:
    name: Build & Unit-Test, Create Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_action == 'build' }}

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Configure CMake Build
      run: cmake -B ${{github.workspace}}/build

    - name: Build HelloWorld App
      run: cmake --build ${{github.workspace}}/build

    - name: Run Unit-Test Gtest
      working-directory: ${{github.workspace}}/build/tst
      run: ./HelloWorldProject_tst

    - name: login to Docker Hub  
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Build Docker image and push to Docker Hub repository
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USER }}/kone-assignment-dockerrepo:${{ github.run_number }}
          ${{ secrets.DOCKERHUB_USER }}/kone-assignment-dockerrepo:latest


  release:
    name: Release-Project
    runs-on: ubuntu-latest
    if: ${{ inputs.perform_action == 'release' }}

    steps:
    - name: Create Release
      if: ${{ vars.RELEASE_ENABLED == 'True' }}
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        body: |
          Changes in this Release
          - First Change1
          - Second Change2
        draft: false
        prerelease: false


